services:

  app:
    build: .
    container_name: hospital_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      APP_NAME: "Sistema de Gestion Hospitalaria"
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: "http://localhost:8000"
      DB_CONNECTION: sqlsrv
      DB_HOST: db
      DB_PORT: 1433
      DB_DATABASE: sistema_gestion_hospitalaria
      DB_USERNAME: sa
      DB_PASSWORD: "Hospital2026*Seguro"
      SESSION_DRIVER: database
      QUEUE_CONNECTION: database
      CACHE_STORE: database
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hospital_sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Hospital2026*Seguro"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data: